services:
  db:
    image: postgres:17
    ports:
      - "5732:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cryptographie
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: